### ISSUE TITLE
Doesn't detect preferred theme

### ISSUE THREAD

**Issue by GetPsyched** [joulev/tailwind-dark-aware#1]
I use Firefox and I have set a background set using `bg-daw-palette-600` and it shows the light version when my system theme is Dark. Note that the Tailwind docs detect my theme just fine, so, my theme is definitely set to dark.

Have set the background colour here: https://github.com/GetPsyched/getpsyched/blob/master/app/globals.css#L8

**Comment by joulev** [comment]
@GetPsyched It's working fine, `bg-daw-palette-600` means `bg-palette-600 dark:bg-palette-400` so the dark mode background is brighter than the light mode background, which is exactly what happens in the recording

https://github.com/joulev/tailwind-dark-aware/assets/44609036/d7e51634-4fff-4d29-a67b-6b2984a44c36

You probably wanted to use `bg-daw-palette-400` instead (use the number for your *light* mode, not your dark mode).

**Comment by GetPsyched** [comment]
Ah! My bad lmao. Should've read the docs more carefully

**Comment by GetPsyched** [comment]
Gonna just put a suggestion in here @joulev: There should be a config option that allows you to invert this behaviour. Good use in my website which is developed with a dark-first design
